In [44]:
import pandas as pd 
import numpy as np

In [ ]:
xl = pd.ExcelFile("Data/Matthieu_Soumaya_Dec2025.xlsx")

# Afficher les noms des feuilles
# print(xl.sheet_names)
# ['Feuille1', 'Feuille2', 'Feuille3']
print(f"Nombre de feuille : ",{len(xl.sheet_names)})
# une par ligne
for nom in xl.sheet_names:
    print(nom)

 Nombre de feuille :  {28}
AGE_SEX_DUREE
Poids_Taille V0
Poids_Taille_V1_3_5
 Mutation_GBA_LRRK2
UPDRS_IV
UPDRSIII_COMPLET_V0_V1
UPDRSIII_COMPLET_V3_V5
UPDRSIII_TOTAUX
ECMP
QUIP
UPPS
MOCA_V0_V3
MOCA_V1_V5
HAMD
HAMA
LARS
PDQ39
DIGITSMT_TRAILMT_DKEFS
CONSO_SPECIFIQUE
Feuil4
LEDD
Feuil1
Feuil2
PSYCHOTROPES
AUTRE_PARKINSON
FREQUENCE_V1_3_5
DATES_VISITE
FIN_ETUDE

## Feuille infos statiques

In [52]:
df_00 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="AGE_SEX_DUREE")
print(df_00.shape)
df_00.head()

(836, 12)

,SUBJID,D_SCREEN,DDN,AGE,SEXE,D_1ER_SYMPT,D_DIAG,D_LDOPA,D_TTT_DOPAM,D_FLUCTU_MOTR,D_FLUCTU_NONMOTR,D_DYSKINESIE
0,Subject Identifier for the Study,date de la visite de screening,date de naissance,âge,sexe,année premiers symptomes,année du diagnostic de la maladie,année d'introduction de la L-DOPA,année d'introduction du traitement dopaminergique,année d'apparition des fluctuations motrices,année d'apparition des fluctuations non motrices,année d'apparition des dyskinésies
1,01-001,18/11/2013,02/1946,67,1,1998,1999,2000,2000,2002,2000,.D
2,01-002,13/01/2014,01/1954,59,1,2006,2006,2006,2006,2011,.K,.K
3,01-003,04/03/2014,02/1953,61,1,2001,2001,2003,2001,2004,.K,2004
4,01-004,12/05/2014,08/1948,65,2,1998,2000,2003,2000,2003,2003,2003

In [53]:
df_01 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name=" Mutation_GBA_LRRK2")
display(df_01.head())
print(df_01.shape)

   SUBJID      DDN   AGE  SEXE Mut_GBA alias_GBA
0  01-001  févr-46  67.0   1.0     NaN       NaN
1  01-002  janv-54  59.0   1.0     NaN       NaN
2  01-003  févr-53  61.0   1.0     NaN       NaN
3  01-004  août-48  65.0   2.0     NaN       NaN
4  01-005   oct-48  65.0   1.0     NaN       NaN

(832, 6)

In [54]:
df_00_01 = pd.merge(df_00, df_01, on="SUBJID", how="left")

In [55]:
df_00_01

,SUBJID,D_SCREEN,DDN_x,AGE_x,SEXE_x,D_1ER_SYMPT,D_DIAG,D_LDOPA,D_TTT_DOPAM,D_FLUCTU_MOTR,D_FLUCTU_NONMOTR,D_DYSKINESIE,DDN_y,AGE_y,SEXE_y,Mut_GBA,alias_GBA
0,Subject Identifier for the Study,date de la visite de screening,date de naissance,âge,sexe,année premiers symptomes,année du diagnostic de la maladie,année d'introduction de la L-DOPA,année d'introduction du traitement dopaminergique,année d'apparition des fluctuations motrices,année d'apparition des fluctuations non motrices,année d'apparition des dyskinésies,NaN,NaN,NaN,NaN,NaN
1,01-001,18/11/2013,02/1946,67,1,1998,1999,2000,2000,2002,2000,.D,févr-46,67.0,1.0,NaN,NaN
2,01-002,13/01/2014,01/1954,59,1,2006,2006,2006,2006,2011,.K,.K,janv-54,59.0,1.0,NaN,NaN
3,01-003,04/03/2014,02/1953,61,1,2001,2001,2003,2001,2004,.K,2004,févr-53,61.0,1.0,NaN,NaN
4,01-004,12/05/2014,08/1948,65,2,1998,2000,2003,2000,2003,2003,2003,août-48,65.0,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,20-025,21/06/2018,09/1956,61,2,2007,2007,2007,2007,2016,2016,2017,sept-56,61.0,2.0,NaN,NaN
832,20-026,04/07/2018,07/1958,59,1,2012,2012,2012,2012,2015,2016,2017,juil-58,59.0,1.0,NaN,NaN
833,20-027,12/07/2018,11/1953,64,1,2011,2012,2015,2013,2017,.A,2018,nov-53,64.0,1.0,GBA,R48W
834,20-028,08/11/2018,10/1949,69,2,2010,2011,2015,2011,2016,2016,2017,oct-49,69.0,2.0,NaN,NaN
835,20-029,28/11/2018,08/1948,70,2,2005,2007,.A,.A,2016,2016,.A,août-48,70.0,2.0,NaN,NaN

In [ ]:
# ══════════════════════════════════════════════════════════
# Afficher les colonnes dupliquées : type + % NaN
# ══════════════════════════════════════════════════════════
print("=" * 65)
print(f"{'Colonne':<20} {'Type _x':<12} {'Type _y':<12} {'NaN _x':>8} {'NaN _y':>8}")
print("=" * 65)

for col_x in cols_x:
    col_y   = col_x.replace("_x", "_y")
    col_nom = col_x.replace("_x", "")
    nan_x   = df_00_01[col_x].isna().mean() * 100
    nan_y   = df_00_01[col_y].isna().mean() * 100
    print(f"{col_nom:<20} {str(df_00_01[col_x].dtype):<12} {str(df_00_01[col_y].dtype):<12} {nan_x:>7.1f}% {nan_y:>7.1f}%")

=================================================================
Colonne              Type _x      Type _y        NaN _x   NaN _y
=================================================================
DDN                  object       object           0.1%     0.8%
AGE                  object       float64          0.2%     1.8%
SEXE                 object       float64          0.2%     1.3%

In [56]:
# ══════════════════════════════════════════════════════════
#Harmoniser les types (_y → même type que _x)
# ══════════════════════════════════════════════════════════
for col_x in cols_x:
    col_y = col_x.replace("_x", "_y")
    try:
        df_00_01[col_y] = df_00_01[col_y].astype(df_00_01[col_x].dtype)
    except (ValueError, TypeError):
        # Si la conversion échoue, on force en string pour pouvoir comparer
        df_00_01[col_x] = df_00_01[col_x].astype(str)
        df_00_01[col_y] = df_00_01[col_y].astype(str)

In [58]:
df_00_01

,SUBJID,D_SCREEN,DDN_x,AGE_x,SEXE_x,D_1ER_SYMPT,D_DIAG,D_LDOPA,D_TTT_DOPAM,D_FLUCTU_MOTR,D_FLUCTU_NONMOTR,D_DYSKINESIE,DDN_y,AGE_y,SEXE_y,Mut_GBA,alias_GBA
0,Subject Identifier for the Study,date de la visite de screening,date de naissance,âge,sexe,année premiers symptomes,année du diagnostic de la maladie,année d'introduction de la L-DOPA,année d'introduction du traitement dopaminergique,année d'apparition des fluctuations motrices,année d'apparition des fluctuations non motrices,année d'apparition des dyskinésies,NaN,NaN,NaN,NaN,NaN
1,01-001,18/11/2013,02/1946,67,1,1998,1999,2000,2000,2002,2000,.D,févr-46,67.0,1.0,NaN,NaN
2,01-002,13/01/2014,01/1954,59,1,2006,2006,2006,2006,2011,.K,.K,janv-54,59.0,1.0,NaN,NaN
3,01-003,04/03/2014,02/1953,61,1,2001,2001,2003,2001,2004,.K,2004,févr-53,61.0,1.0,NaN,NaN
4,01-004,12/05/2014,08/1948,65,2,1998,2000,2003,2000,2003,2003,2003,août-48,65.0,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,20-025,21/06/2018,09/1956,61,2,2007,2007,2007,2007,2016,2016,2017,sept-56,61.0,2.0,NaN,NaN
832,20-026,04/07/2018,07/1958,59,1,2012,2012,2012,2012,2015,2016,2017,juil-58,59.0,1.0,NaN,NaN
833,20-027,12/07/2018,11/1953,64,1,2011,2012,2015,2013,2017,.A,2018,nov-53,64.0,1.0,GBA,R48W
834,20-028,08/11/2018,10/1949,69,2,2010,2011,2015,2011,2016,2016,2017,oct-49,69.0,2.0,NaN,NaN
835,20-029,28/11/2018,08/1948,70,2,2005,2007,.A,.A,2016,2016,.A,août-48,70.0,2.0,NaN,NaN

In [ ]:
# # ══════════════════════════════════════════════════════════
# # Comparer les valeurs et afficher la similarité
# # ══════════════════════════════════════════════════════════
# print("\n" + "=" * 50)
# print(f"{'Colonne':<20} {'Similarité':>12} {'Statut'}")
# print("=" * 50)

# resultats = {}
# for col_x in cols_x:
#     col_y   = col_x.replace("_x", "_y")
#     col_nom = col_x.replace("_x", "")

#     # Comparer uniquement les lignes où les deux sont non-NaN
#     masque  = df_00_01[col_x].notna() & df_00_01[col_y].notna()
#     n_total = masque.sum()

#     if n_total == 0:
#         similarite = 0.0
#     else:
#         n_egaux    = (df_00_01.loc[masque, col_x] == df_00_01.loc[masque, col_y]).sum()
#         similarite = (n_egaux / n_total) * 100

#     statut = "identiques" if similarite == 100 else f"  {100-similarite:.1f}% différences"
#     print(f"{col_nom:<20} {similarite:>11.1f}% {statut}")
#     resultats[col_nom] = similarite

==================================================
Colonne                Similarité Statut
==================================================
DDN                          0.0%   100.0% différences
AGE                          0.0%   100.0% différences
SEXE                         0.0%   100.0% différences

In [43]:
for col_x in cols_x:
    col_y   = col_x.replace("_x", "_y")
    col_nom = col_x.replace("_x", "")

    # Lignes où _x est NaN mais _y est rempli
    masque = df_00_01[col_x].isna() & df_00_01[col_y].notna()
    lignes = df_00_01[masque][["SUBJID", col_x, col_y]]

    if len(lignes) > 0:
        print(f"\n{'='*50}")
        print(f"{col_nom} — {len(lignes)} ligne(s) à combler")
        print(lignes.to_string(index=False))

In [59]:
# ══════════════════════════════════════════════════════════
#  Fusionner et combler les NaN
# ══════════════════════════════════════════════════════════
for col_x in cols_x:
    col_y   = col_x.replace("_x", "_y")
    col_nom = col_x.replace("_x", "")
    # Colonnes identiques → on garde _x et on comble ses NaN avec _y
    df_00_01[col_nom] = df_00_01[col_x].fillna(df_00_01[col_y])
    df_00_01.drop(columns=[col_x, col_y], inplace=True)
    print(f"{col_nom} : fusionné (NaN comblés depuis _y)")

DDN : fusionné (NaN comblés depuis _y)
AGE : fusionné (NaN comblés depuis _y)
SEXE : fusionné (NaN comblés depuis _y)

In [ ]:

# supprimer la premiére ligne 
df_00_01 = df_00_01.iloc[1:].reset_index(drop=True)


# # Ignorer directement à la lecture
# df = pd.read_excel("fichier.xlsx", skiprows=1)

In [51]:
df_00_01

,SUBJID,D_SCREEN,D_1ER_SYMPT,D_DIAG,D_LDOPA,D_TTT_DOPAM,D_FLUCTU_MOTR,D_FLUCTU_NONMOTR,D_DYSKINESIE,Mut_GBA,alias_GBA,DDN,AGE,SEXE
0,01-001,18/11/2013,1998,1999,2000,2000,2002,2000,.D,NaN,NaN,02/1946,67,1
1,01-002,13/01/2014,2006,2006,2006,2006,2011,.K,.K,NaN,NaN,01/1954,59,1
2,01-003,04/03/2014,2001,2001,2003,2001,2004,.K,2004,NaN,NaN,02/1953,61,1
3,01-004,12/05/2014,1998,2000,2003,2000,2003,2003,2003,NaN,NaN,08/1948,65,2
4,01-005,16/06/2014,1997,1998,2012,1998,2012,.A,.A,NaN,NaN,10/1948,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,20-025,21/06/2018,2007,2007,2007,2007,2016,2016,2017,NaN,NaN,09/1956,61,2
831,20-026,04/07/2018,2012,2012,2012,2012,2015,2016,2017,NaN,NaN,07/1958,59,1
832,20-027,12/07/2018,2011,2012,2015,2013,2017,.A,2018,GBA,R48W,11/1953,64,1
833,20-028,08/11/2018,2010,2011,2015,2011,2016,2016,2017,NaN,NaN,10/1949,69,2
834,20-029,28/11/2018,2005,2007,.A,.A,2016,2016,.A,NaN,NaN,08/1948,70,2

In [64]:
df_00_01.to_excel("Output/info_statiques.xlsx",index=False)

## Feuille Bilan

### Séparer les Feuilles

#### Poids_Taille_V1_3_5

In [66]:
df_v1_2_3 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="Poids_Taille_V1_3_5")
print(df_v1_2_3.shape)
df_v1_2_3.head()

(2506, 8)

,SUBJID,INIT_PAT,TITRE,DATE,POIDS,POIDS_NR,TAILLE,TAILLE_NR
0,Subject Identifier for the Study,initiales patient,titre,Date de la visite,poids,poids non realisé,taille,taille non réalisé
1,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN
2,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN
4,01-002,TM,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN

In [68]:
df_v1_2_3["TITRE"].value_counts()

TITRE
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [186]:
# Séparer le dataset par valeur de la colonne TITRE
df_v1_Poids_Taille = df_v1_2_3[df_v1_2_3["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_Poids_Taille = df_v1_2_3[df_v1_2_3["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_Poids_Taille = df_v1_2_3[df_v1_2_3["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

In [75]:
df_v1

,SUBJID,INIT_PAT,TITRE,DATE,POIDS,POIDS_NR,TAILLE,TAILLE_NR
0,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN
1,01-002,TM,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN
2,01-003,SJ,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN
3,01-004,DJ,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN
4,01-005,LB,Visite Bilan à 1 an - V1,25/01/2016,82,NaN,169,NaN
...,...,...,...,...,...,...,...,...
830,20-025,DA,Visite Bilan à 1 an - V1,22/09/2021,75,NaN,170,NaN
831,20-026,ME,Visite Bilan à 1 an - V1,.A,NaN,1,NaN,1
832,20-027,RP,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN
833,20-028,DN,Visite Bilan à 1 an - V1,10/11/2021,82,NaN,162,NaN
834,20-029,DA,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN

#### UPDRS_IV

In [79]:
df_UPDRS_IV = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="UPDRS_IV")
print(df_UPDRS_IV.shape)
df_UPDRS_IV.head()

(3341, 10)

,SUBJID,INIT_PAT,TITRE,MDSUPDRSPARTIE4,MDSUPDRSPARTIE41,MDSUPDRSPARTIE42,MDSUPDRSPARTIE43,MDSUPDRSPARTIE44,MDSUPDRSPARTIE45,MDSUPDRSPARTIE46
0,Subject Identifier for the Study,initiales patient,titre,MDS-UPDRS partie 4,MDS-UPDRS partie 4.1,MDS-UPDRS partie 4.2,MDS-UPDRS partie 4.3,MDS-UPDRS partie 4.4,MDS-UPDRS partie 4.5,MDS-UPDRS partie 4.6
1,01-001,SR,Visite de screening,10,Minime,Modéré,Léger,Modéré,Minime,Normal
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
df_UPDRS_IV["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [185]:
# Séparer le dataset par valeur de la colonne TITRE
df_V0_UPDRS = df_UPDRS_IV[df_UPDRS_IV["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v1_UPDRS = df_UPDRS_IV[df_UPDRS_IV["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_UPDRS = df_UPDRS_IV[df_UPDRS_IV["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_UPDRS = df_UPDRS_IV[df_UPDRS_IV["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### UPDRSIII_COMPLET_V0_V1

In [ ]:
df_UPDRSIII_COMPLET_V0_V1 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="UPDRSIII_COMPLET_V0_V1")
print(df_UPDRSIII_COMPLET_V0_V1.shape)
df_UPDRSIII_COMPLET_V0_V1.head()

(836, 417)

,SUBJID,V12H_APRES,DEMIVIE_AGONISTE,H_LDOPA,DOSE_LDOPA,OFF_H,ON_H15,ON_H30,ON_H45,ON_H60,...,OFFON_SS_TOT1_CALC,ON_SS_TOT1_CALC,ONOFF_SS_TOT2_CALC,OFF_SS_TOT2_CALC,OFFON_SS_TOT2_CALC,ON_SS_TOT2_CALC,ONOFF_TOTALCALC,OFF_TOTALCALC,OFFON_TOTALCALC,ON_TOTALCALC
0,Subject Identifier for the Study,réalisation après 12h d'arret L-Dopa,réalisation après 5 demie-vies d'arret agoniste,heure de prise de L Dopa,dose de L Dopa,off heure,on 15 heure,on 30 heure,on 45 heure,on 60 heure,...,OFFON_ss_tot1_calc,ON_ss_tot1_calc,ONOFF_ss_tot2_calc,OFF_ss_tot2_calc,OFFON_ss_tot2_calc,ON_ss_tot2_calc,ONOFF_TOTALCALC,OFF_TOTALCALC,OFFON_TOTALCALC,ON_TOTALCALC
1,01-001,1,1,09:00,200,09:00,09:15,09:30,09:45,10:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-002,1,1,09:47,350,09:46,10:10,10:25,10:43,11:03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-003,1,.K,09:00,400,08:50,09:17,09:34,09:54,10:14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-004,1,1,09:25,500,09:20,09:46,10:06,10:30,10:45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### UPDRSIII_COMPLET_V3_V5

In [90]:
df_UPDRSIII_COMPLET_V3_V5 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="UPDRSIII_COMPLET_V3_V5 ")
print(df_UPDRSIII_COMPLET_V3_V5.shape)
df_UPDRSIII_COMPLET_V3_V5.head()

(1671, 41)

,SUBJID,VISIT,H_DERNPRISE_DOPA,ON_H,ON_PAROLE,ON_EXP_FAC,ON_COU,ON_MSDROIT_RIG,ON_MSGCHE_RIG,ON_MIDROIT_RIG,...,ON_TREMBLMAIN_MSDROIT,ON_TREMBLMAIN_MSGCHE,ON_LEVRE_AMPLI_TREMBL,ON_MSDROIT_AMPLI_TREMBL,ON_MSGCHE_AMPLI_TREMBL,ON_MIDROIT_AMPLI_TREMBL,ON_MIGCHE_AMPLI_TREMBL,ON_CONSTANCE_TREMBL,ON_SS_TOT2,ON_TOTAL
0,Subject Identifier for the Study,Visit,heure de dernière prise de traitement dopamine...,heure en minute,parole,expression faciale,rigidité cou,rigidité MS droit,rigidité MS gauche,rigidité MI droit,...,tremblement action mains MS droit,tremblement action mains MS gauche,amplitude tremblement repos lèvre/mâchoire,amplitude tremblement repos MS droit,amplitude tremblement repos MS gauche,amplitude tremblement repos MI droit,amplitude tremblement repos MI gauche,constance tremblement,sous total 2,TOTAL
1,01-001,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,01-001,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,01-002,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
4,01-002,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

In [91]:
df_UPDRSIII_COMPLET_V3_V5["VISIT"].value_counts()

VISIT
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
Visit                          1
Name: count, dtype: int64

In [184]:
# Séparer le dataset par valeur de la colonne TITRE
df_v3_UPDRSIII_COMPLET = df_v1_2_3[df_v1_2_3["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_UPDRSIII_COMPLET = df_v1_2_3[df_v1_2_3["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### UPDRSIII_TOTAUX

#### ECMP

In [93]:
df_ECMP = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="ECMP")
print(df_ECMP.shape)
df_ECMP.head()

(3341, 45)

,SUBJID,INIT_PAT,TITRE,HUMEUR_DEPRE,HUMEUR_DEPRE_ATCD,ANXIETE,ANXIETE_ATCD,IRRITABI_AGRESS,IRRITABI_AGRESS_ATCD,HYPEREMOT,...,ACHATS_COMPULSIFS,ACHATS_COMPULSIFS_ATCD,JEU_PATHOLQ,JEU_PATHOLQ_ATCD,HYPERSEXUALIT,HYPERSEXUALIT_ATCD,ADDICTION_DOPA,ADDICTION_DOPA_ATCD,MODE_APPETITIF,MODE_APPETITIF_ATCD
0,Subject Identifier for the Study,initiales patient,titre,humeur dépressive,humeur dépressive antécédents,anxiete,anxiété antécédents,"irritabilité, agressivité","irritabilité, agressivité antécédents",hyperémotivité,...,achats compulsifs,achats compulsifs antécédents,jeu pathologique,jeu pathologique antécédents,hypersexualité,hypersexualité antécédents,addiction dopaminergique,addiction dopaminergique antécédents,mode appétitif,mode appétitif antécédents
1,01-001,SR,Visite de screening,0,OUI,1,NaN,1,NaN,0,...,0,NaN,0,NaN,0,OUI,0,NaN,0,NaN
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
df_ECMP["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [182]:
# Séparer le dataset par valeur de la colonne TITRE
df_V0_ECMP = df_ECMP[df_ECMP["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v1_ECMP = df_ECMP[df_ECMP["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_ECMP = df_ECMP[df_ECMP["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_ECMP = df_ECMP[df_ECMP["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### QUIP

In [97]:
df_QUIP = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="QUIP ")
print(df_QUIP.shape)
df_QUIP.head()

(3341, 34)

,SUBJID,INIT_PAT,TITRE,RENSEIGNMT,QUIP_A1_JEU,QUIP_A1_SEXE,QUIP_A1_ACHATS,QUIP_A1_PULSIONS_ALIM,QUEST2_JEU,QUEST2_SEXE,...,QUIP_B1A,QUIP_B1B,QUIP_B1C,QUIP_B2,QUIP_B3,QUIP_C1,QUIP_C2,QUIP_C3,QUIP_C4,QUIP_C5
0,Subject Identifier for the Study,initiales patient,titre,renseignements,QUIP_A1_jeu,QUIP_A1_sexe,QUIP_A1_achats,QUIP_A1_pulsions_alimentaires,question 2 jeu,question 2 sexualité,...,autres comportemetns question 1a,autres comportemetns question 1b,autres comportemetns question 1c,autres comportemetns question 2,autres comportemetns question 3,usage des médicaments question 1,usage des médicaments question 2,usage des médicaments question 3,usage des médicaments question 4,usage des médicaments question 5
1,01-001,SR,Visite de screening,1,0,1,0,0,0,1,...,1,0,0,0,0,1,0,0,0,0
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
df_QUIP["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [181]:
# Séparer le dataset par valeur de la colonne TITRE
df_V0_QUIP = df_QUIP[df_QUIP["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v1_QUIP = df_QUIP[df_QUIP["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_QUIP = df_QUIP[df_QUIP["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_QUIP = df_QUIP[df_QUIP["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### UPPS

In [101]:
df_UPPS = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="UPPS")
print(df_UPPS.shape)
df_UPPS.head()

(3341, 23)

,SUBJID,INIT_PAT,TITRE,UPPS1,UPPS2,UPPS3,UPPS4,UPPS5,UPPS6,UPPS7,...,UPPS11,UPPS12,UPPS13,UPPS14,UPPS15,UPPS16,UPPS17,UPPS18,UPPS19,UPPS20
0,Subject Identifier for the Study,initiales patient,titre,UPPS1,UPPS2,UPPS3,UPPS4,UPPS5,UPPS6,UPPS7,...,UPPS11,UPPS12,UPPS13,UPPS14,UPPS15,UPPS16,UPPS17,UPPS18,UPPS19,UPPS20
1,01-001,SR,Visite de screening,1,2,3,4,1,1,4,...,1,4,1,4,4,1,4,1,1,3
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
df_UPPS["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [180]:
# Séparer le dataset par valeur de la colonne TITRE
df_V0_QUIP = df_QUIP[df_QUIP["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v1_QUIP = df_QUIP[df_QUIP["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_QUIP = df_QUIP[df_QUIP["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_QUIP = df_QUIP[df_QUIP["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### MOCA_V0_V3

In [104]:
df_MOCA_V0_V3 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="MOCA_V0_V3")
print(df_MOCA_V0_V3.shape)
df_MOCA_V0_V3.head()

(1671, 15)

,SUBJID,INIT_PAT,TITRE,AGEINF12,MOCA_VISUO,MOCA_DENOM,MOCA_ATTENTION1,MOCA_ATTENTION2,MOCA_ATTENTION3,MOCA_LANGAGE1,MOCA_LANGAGE2,MOCA_ABSTAC,MOCA_RAPPEL,MOCA_ORIENTATION,MOCA_SCORE
0,Subject Identifier for the Study,initiales patient,titre,Age inférieur ou égal à 12 ans,MoCA Visuospatial/exécutif,MoCA dénomination,MoCA attention,MoCA attention 2,MoCA attention 3,MoCA langage,MoCA langage 2,MoCA abstraction,MoCA rappel,MoCA orientation,MoCA score total
1,01-001,SR,Visite de screening,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-002,TM,Visite de screening,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-002,TM,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
df_MOCA_V0_V3["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 3 ans - V3    835
titre                          1
Name: count, dtype: int64

In [179]:
# Séparer le dataset par valeur de la colonne TITRE
df_V0_MOCA = df_MOCA_V0_V3[df_MOCA_V0_V3["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v3_MOCA = df_MOCA_V0_V3[df_MOCA_V0_V3["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)

#### MOCA_V1_V5

In [107]:
df_MOCA_V1_V5 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="MOCA_V1_V5")
print(df_MOCA_V1_V5.shape)
df_MOCA_V1_V5.head()

(1671, 15)

,SUBJID,INIT_PAT,TITRE,SCOLINF12,MOCA_VISUO,MOCA_DENOM,MOCA_ATTENTION1,MOCA_ATTENTION2,MOCA_ATTENTION3,MOCA_LANGAGE1,MOCA_LANGAGE2,MOCA_ABSTAC,MOCA_RAPPEL,MOCA_ORIENTATION,MOCA_SCORE
0,Subject Identifier for the Study,initiales patient,titre,Scolarité inférieure ou égale à 12 ans,MoCA visuospatial/éxécutif,MoCA dénomination,MoCA attention 1,MoCA attention 2,MoCA attention 3,MoCA langage 1,MoCA langage 2,MoCA abstraction,MoCA rappel,MoCA orientation,MoCA score
1,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-002,TM,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-002,TM,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
df_MOCA_V1_V5["TITRE"].value_counts()

TITRE
Visite Bilan à 1 an - V1     835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [178]:
# Séparer le dataset par valeur de la colonne TITRE
df_v1_MOCA = df_MOCA_V1_V5[df_MOCA_V1_V5["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v5_MOCA = df_MOCA_V1_V5[df_MOCA_V1_V5["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### HAMD

In [110]:
df_HAMD = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="HAMD")
print(df_HAMD.shape)
df_HAMD.head()

(3341, 23)

,SUBJID,INIT_PAT,TITRE,HAMD_1,HAMD_2,HAMD_3,HAMD_4,HAMD_5,HAMD_6,HAMD_7,...,HAMD_11,HAMD_12,HAMD_13,HAMD_14,HAMD_15,HAMD_16A,HAMD_16B,HAMD_17,HAMD_SCORECALC,DEPRESSION
0,Subject Identifier for the Study,initiales patient,titr,Hamilton 1,Hamilton 2,Hamilton 3,Hamilton 4,Hamilton 5,Hamilton 6,Hamilton 7,...,Hamilton 11,Hamilton 12,Hamilton 13,Hamilton 14,Hamilton 15,Hamilton 16A,Hamilton 16B,Hamilton 17,Hamilton calcul,échelle de dépression
1,01-001,SR,Visite de screening,0,0,0,0,0,0,1,...,2,0,0,0,0,0,NaN,0,4,Symptomes dépressifs légers
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
df_HAMD["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titr                           1
Name: count, dtype: int64

In [177]:
# Séparer le dataset par valeur de la colonne TITRE
df_V0_HAMD = df_HAMD[df_HAMD["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v1_HAMD = df_HAMD[df_HAMD["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_HAMD = df_HAMD[df_HAMD["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_HAMD = df_HAMD[df_HAMD["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### HAMA

In [114]:
df_HAMA = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="HAMA ")
print(df_HAMA.shape)
df_HAMA.head()

(3341, 19)

,SUBJID,INIT_PAT,TITRE,HAMA_HUM_ANX,HAMA_TENSION,HAMA_PEURS,HAMA_INSOMN,HAMA_FCT_INTEL,HAMA_HUM_AGRESS,HAMA_MUSCUL,HAMA_SENSOR,HAMA_SYMPTCV,HAMA_SYMPT_RESPI,HAMA_SYMPT_GASTRO,HAMA_GENITO,HAMA_SNA,HAMA_COMPORT_ENTRETIEN,HAMA_SCORECALC,ANXIETE
0,Subject Identifier for the Study,initiales patient,titre,Hamilton humeur anxieuse,Hamilton tension,Hamilton peurs,Hamilton insomnie,Hamilton fonctions intellectuelles,Hamilton humeur dépressive,Hamilton symptomes somatiques généraux muscula...,Hamilton symptomes somaiques généraux sensoriels,Hamilton symptomes cardio-vasculaire,Hamilton symtpomes respiratoires,Hamilton symptomes gastro-intestinaux,Hamilton symptomes génito-urinaire,Hamilton système nerveux autonome,Hamilton comportemetn pendant l'entretien,Hamilton calcul,évaluation de l'anxiété
1,01-001,SR,Visite de screening,Léger,Absent,Absent,Absent,Absent,Absent,Absent,Absent,Absent,Modéré,Absent,Absent,Absent,Absent,3,Anxiété légère
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
df_HAMA["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [176]:
# Séparer le dataset par valeur de la colonne TITRE
df_V0_HAMA = df_HAMA[df_HAMA["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v1_HAMA = df_HAMA[df_HAMA["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_HAMA = df_HAMA[df_HAMA["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_HAMA = df_HAMA[df_HAMA["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### LARS

In [117]:
df_LARS = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="LARS ")
print(df_LARS.shape)
df_LARS.head()

(3341, 14)

,SUBJID,INIT_PAT,TITRE,LARS_EP,LARS_INT,LARS_INI,LARS_NS,LARS_M,LARS_ER,LARS_C,LARS_SL,LARS_SA,LARS_SCORE,LARS_RESULTAT
0,Subject Identifier for the Study,initiales patient,titre,LARS activités de la vie quotidienne,LARS centres d'intérets,LARS prises d'initiative,LARS intéret pour la nouveauté,LARS motivation - efforts volontaires,LARS intensité des émotions,LARS inquiétude,LARS vie sociale,LARS capacité d'auto-critique,LARS score,Score LARS résultats
1,01-001,SR,Visite de screening,-4,0,-4,-4,-4,-4,-4,-3,-4,-31,Non apathique
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
df_LARS["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [175]:
# Séparer le dataset par valeur de la colonne TITRE
df_V0_LARS = df_LARS[df_LARS["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v1_LARS = df_LARS[df_LARS["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_LARS = df_LARS[df_LARS["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_LARS = df_LARS[df_LARS["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### PDQ39

In [121]:
df_PDQ39 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="PDQ39")
print(df_PDQ39.shape)
df_PDQ39.head()

(3341, 45)

,SUBJID,VISIT,INIT_PAT,SITUATION_MARITALE,PDQ39_1,PDQ39_2,PDQ39_3,PDQ39_4,PDQ39_5,PDQ39_6,...,PDQ39_32,PDQ39_33,PDQ39_34,REF_SITU_FAM,PDQ39_35,PDQ39_36,PDQ39_37,PDQ39_38,PDQ39_39,PDQ39_SCORE
0,Subject Identifier for the Study,Visit,initiales patient,situation maritale,PDQ39-1,PDQ39-2,PDQ39-3,PDQ39-4,PDQ39-5,PDQ39-6,...,PDQ39_32,PDQ39_33,PDQ39_34,référence situation familiale,PDQ39_35,PDQ39_36,PDQ39_37,PDQ39_38,PDQ39_39,score PDQ39
1,01-001,Visite de screening,SR,Oui,Rarement,Jamais,Parfois,Toujours ou ne peut jamais faire,Parfois,Rarement,...,Rarement,Jamais,Parfois,1,Rarement,Rarement,Parfois,Parfois,Rarement,50
2,01-001,Visite Bilan à 1 an - V1,SR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,Visite Bilan à 3 ans - V3,SR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,Visite Bilan à 5 ans - V5,SR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
df_PDQ39["VISIT"].value_counts()

VISIT
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
Visit                          1
Name: count, dtype: int64

In [174]:
# Séparer le dataset par valeur de la colonne VISIT
df_V0_PDQ39 = df_PDQ39[df_PDQ39["VISIT"] == "Visite de screening"].reset_index(drop=True)
df_v1_PDQ39 = df_PDQ39[df_PDQ39["VISIT"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_PDQ39 = df_PDQ39[df_PDQ39["VISIT"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_PDQ39 = df_PDQ39[df_PDQ39["VISIT"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### DIGITSMT_TRAILMT_DKEFS

In [125]:
df_DIGITSMT_TRAILMT_DKEFS = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="DIGITSMT_TRAILMT_DKEFS")
print(df_DIGITSMT_TRAILMT_DKEFS.shape)
df_DIGITSMT_TRAILMT_DKEFS.head()

(3341, 22)

,SUBJID,INIT_PAT,TITRE,DIGITSMT_NBSUBSTI,DIGITSMT_NBCORRECT,TRAILMT_ALPHABET,TRAILMT_CHIFFRE,TRAILMT_LETTRECHIFFRE,TRAILMT_NB_ERREURS,DKEFS_TPS1,...,DKEFS_TPS2,DKEFS_NBERR2,DKEFS_AUTOCORR2,DKEFS_TPS3,DKEFS_NBERR3,DKEFS_AUTOCORR3,DKEFS_TPS4,DKEFS_NBERR4,DKEFS_AUTOCORR4,BENTON_NBCORR
0,Subject Identifier for the Study,initiales patient,titre,Digit Symbol Modalities Test nombre total de s...,Digit Symbol Modalities Test nombre de substit...,"récitation de l'alphabet, temps en secondes","comptage de 1 à 26, temps en secondes","alternance lettres/nombres, temps en secondes","alternance lettres/nombres, erreurs","DK-EFS partie 1, temps",...,"DK-EFS partie 2, temps","DK-EFS partie 2, nombre d'erreurs","DK-EFS partie 2, nombre d'auto-corrections","DK-EFS partie 3, temps","DK-EFS partie 3, nombre d'erreurs","DK-EFS partie 3, nombre d'auto-corrections","DK-EFS partie 4, temps","DK-EFS partie 4, nombre d'erreurs","DK-EFS partie 4, nombre d'auto-corrections","Benton Judgement of Line Orientation test, nom..."
1,01-001,SR,Visite de screening,38,37,.D,.D,.D,.D,.D,...,.D,.D,.D,.D,.D,.D,.D,.D,.D,10
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [126]:
df_DIGITSMT_TRAILMT_DKEFS["TITRE"].value_counts()

TITRE
Visite de screening          835
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
titre                          1
Name: count, dtype: int64

In [173]:
# Séparer le dataset par valeur de la colonne VISIT
df_V0_DIGITSMT_TRAILMT_DKEFS = df_DIGITSMT_TRAILMT_DKEFS[df_DIGITSMT_TRAILMT_DKEFS["TITRE"] == "Visite de screening"].reset_index(drop=True)
df_v1_DIGITSMT_TRAILMT_DKEFS = df_DIGITSMT_TRAILMT_DKEFS[df_DIGITSMT_TRAILMT_DKEFS["TITRE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_DIGITSMT_TRAILMT_DKEFS = df_DIGITSMT_TRAILMT_DKEFS[df_DIGITSMT_TRAILMT_DKEFS["TITRE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_DIGITSMT_TRAILMT_DKEFS = df_DIGITSMT_TRAILMT_DKEFS[df_DIGITSMT_TRAILMT_DKEFS["TITRE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### CONSO_SPECIFIQUE

In [129]:
df_CONSO_SPECIFIQUE = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="CONSO_SPECIFIQUE ")
print(df_CONSO_SPECIFIQUE.shape)
df_CONSO_SPECIFIQUE.head()

(4176, 113)

,SUBJID,VISIT,NUM,VISIT_NOM,NUM_CENTRE,NUM_PAT,INIT_PAT,MEDICMT1,POSO1,CAT_TRT_ANTIPARK1,...,CONCAT_4,CONCAT_5,CONCAT_6,CONCAT_7,CONCAT_8,CONCAT_9,CONCAT_10,CONCAT_11,CONCAT_12,CONCAT_13
0,Subject Identifier for the Study,Visit,Num,VISIT_NOM,numéro centre,numéro patient,initiales patient,médicament 1,posologie 1,catégorie traitement antipakinsonien 1,...,concaténation 4,concaténation 5,concaténation 6,concaténation 7,concaténation 8,concaténation 9,concaténation 10,concaténation 11,concaténation 12,concaténation 13
1,01-001,Traitements concomittants antiparkinsoniens sp...,1,Screening,01,001,SR,NaN,200 MG LDOPA,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-001,Traitements concomittants antiparkinsoniens sp...,2,Post op,01,001,SR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,Traitements concomittants antiparkinsoniens sp...,3,V1,01,001,SR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,Traitements concomittants antiparkinsoniens sp...,4,V3,01,001,SR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [131]:
df_CONSO_SPECIFIQUE["NUM"].value_counts()

NUM
1      835
2      835
3      835
4      835
5      835
Num      1
Name: count, dtype: int64

In [172]:
# Séparer le dataset par valeur de la colonne VISIT
df_V0_CONSO_SPECIFIQUE = df_CONSO_SPECIFIQUE[df_CONSO_SPECIFIQUE["NUM"] == "1"].reset_index(drop=True)
df_vc_CONSO_SPECIFIQUE = df_CONSO_SPECIFIQUE[df_CONSO_SPECIFIQUE["NUM"] == "2"].reset_index(drop=True)
df_v1_CONSO_SPECIFIQUE = df_CONSO_SPECIFIQUE[df_CONSO_SPECIFIQUE["NUM"] == "3"].reset_index(drop=True)
df_v3_CONSO_SPECIFIQUE = df_CONSO_SPECIFIQUE[df_CONSO_SPECIFIQUE["NUM"] == "4"].reset_index(drop=True)
df_v5_CONSO_SPECIFIQUE = df_CONSO_SPECIFIQUE[df_CONSO_SPECIFIQUE["NUM"] == "5"].reset_index(drop=True)

#### Feuil4

In [134]:
df_Feuil4 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="Feuil4")
print(df_Feuil4.shape)
df_Feuil4.head()

(807, 7)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Somme de v,Étiquettes de colonnes,NaN,NaN,NaN,NaN,NaN
2,Étiquettes de lignes,1,2.0,3.0,4.0,5.0,Total général
3,01-001,1,NaN,NaN,NaN,NaN,1
4,01-002,1,NaN,NaN,NaN,NaN,1

#### LEDD

In [136]:
df_LEDD = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="LEDD")
print(df_LEDD.shape)
df_LEDD.head()

(2395, 37)

,v,Subject Identifier for the Study,Visit,Num,médicament 1,posologie 1,médicament 2,posologie 2,médicament 3,posologie 3,...,posologie 12,médicament 13,posologie 13,ledd_levo,fact_icomt,ledd_levot,ledd_agot,ledd_imaobt,ledd_mantt,ledd_tot
0,1,01-001,Traitements concomittants antiparkinsoniens sp...,1,NaN,200 MG LDOPA,MODOPAR 125 LP,100 MG L DOPA,STALEVO 75 MG,5X75= 250 MG L DOPA,...,NaN,NaN,NaN,550.0,1.33,731.5,240.0,NaN,400.0,1371.5
1,1,01-002,Traitements concomittants antiparkinsoniens sp...,1,REQUIP,LP 24 MG 1 PAR JOUR,AZILECT,1 MG LE MATIN,MODOPAR,125 MG LP 2 AU COUCHER,...,NaN,NaN,NaN,1300.0,1.33,1729.0,480.0,100.0,NaN,2309.0
2,1,01-003,Traitements concomittants antiparkinsoniens sp...,1,STALEVO 200,4 / JOUR,STALEVO 150,3 / JOUR,AZILECT,1MG,...,NaN,NaN,NaN,1350.0,1.33,1795.5,NaN,100.0,NaN,1895.5
3,1,01-004,Traitements concomittants antiparkinsoniens sp...,1,MODOPAR 125 DISPERSIBLE,3 CP LE MATIN,MODOPAR 125 GELULES,7 PAR JOUR,SINEMET LP 100,2 LE SOIR,...,NaN,NaN,NaN,1150.0,1.00,1150.0,480.0,NaN,NaN,1630.0
4,1,01-004,Traitements concomittants antiparkinsoniens sp...,2,ROPINIROLE LP,6MG,SINEMET LP,200MG,MODOPAR 125,300MG,...,NaN,NaN,NaN,700.0,1.00,700.0,120.0,NaN,NaN,820.0

In [139]:
df_LEDD["Num"].value_counts()

Num
1    794
3    525
2    491
5    313
4    272
Name: count, dtype: int64

In [234]:
# Séparer le dataset par valeur de la colonne VISIT
df_V0_LEDD = df_LEDD[df_LEDD["Num"] == 1].reset_index(drop=True)
df_vc_LEDD = df_LEDD[df_LEDD["Num"] == 2].reset_index(drop=True)
df_v1_LEDD = df_LEDD[df_LEDD["Num"] == 3].reset_index(drop=True)
df_v3_LEDD = df_LEDD[df_LEDD["Num"] == 4].reset_index(drop=True)
df_v5_LEDD = df_LEDD[df_LEDD["Num"] == 5].reset_index(drop=True)

#### Feuil1

In [142]:
df_Feuil1 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="Feuil1")
print(df_Feuil1.shape)
df_Feuil1.head()

(2395, 7)

,Subject Identifier for the Study,Num,ledd_levot,ledd_agot,ledd_imaobt,ledd_mantt,ledd_tot
0,01-001,1,731.5,240.0,NaN,400.0,1371.5
1,01-002,1,1729.0,480.0,100.0,NaN,2309.0
2,01-003,1,1795.5,NaN,100.0,NaN,1895.5
3,01-004,1,1150.0,480.0,NaN,NaN,1630.0
4,01-004,2,700.0,120.0,NaN,NaN,820.0

In [143]:
df_Feuil1["Num"].value_counts()

Num
1    794
3    525
2    491
5    313
4    272
Name: count, dtype: int64

In [232]:
# Séparer le dataset par valeur de la colonne VISIT
df_V0_Feuil1 = df_Feuil1[df_Feuil1["Num"] == 1].reset_index(drop=True)
df_vc_Feuil1 = df_Feuil1[df_Feuil1["Num"] == 2].reset_index(drop=True)
df_v1_Feuil1 = df_Feuil1[df_Feuil1["Num"] == 3].reset_index(drop=True)
df_v3_Feuil1 = df_Feuil1[df_Feuil1["Num"] == 4].reset_index(drop=True)
df_v5_Feuil1 = df_Feuil1[df_Feuil1["Num"] == 5].reset_index(drop=True)

#### Feuil2

In [146]:
df_Feuil2 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="Feuil2")
print(df_Feuil2.shape)
df_Feuil2.head()

(834, 10)

,Subject Identifier for the Study,Num,ledd_levot,ledd_agot,ledd_imaobt,ledd_mantt,ledd_tot,Unnamed: 7,Unnamed: 8,01-001
0,01-001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-002
1,01-002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-003
2,01-003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-004
3,01-004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-005
4,01-005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-006

#### PSYCHOTROPES

In [148]:
df_PSYCHOTROPES = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="PSYCHOTROPES")
print(df_PSYCHOTROPES.shape)
df_PSYCHOTROPES.head()

(4176, 83)

,SUBJID,VISIT,NUM,Unnamed: 3,INIT_PAT,MEDICMT1,D_DEB1,POSO1,INDIC1,D_FIN1,...,POSO12,INDIC12,D_FIN12,ENCOURS12,MEDICMT13,D_DEB13,POSO13,INDIC13,D_FIN13,ENCOURS13
0,Subject Identifier for the Study,Visit,Num,NaN,initiales patient,médicament 1,date de début 1,posologie 1,indication 1,date de fin 1,...,posologie 12,indication 12,date de fin 12,en cours 12,médicament 13,date de début 13,posologie 13,indication 13,date de fin 13,en cours 13
1,01-001,Les traitements psychotropes,1,V0,SR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-001,Les traitements psychotropes,2,Vc,SR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,Les traitements psychotropes,3,V1,SR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,Les traitements psychotropes,4,V3,SR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
df_PSYCHOTROPES["NUM"].value_counts()

NUM
1      835
2      835
3      835
4      835
5      835
Num      1
Name: count, dtype: int64

In [152]:
# Séparer le dataset par valeur de la colonne VISIT
df_V0_PSYCHOTROPES = df_PSYCHOTROPES[df_PSYCHOTROPES["NUM"] == "1"].reset_index(drop=True)
df_vc_PSYCHOTROPES = df_PSYCHOTROPES[df_PSYCHOTROPES["NUM"] == "2"].reset_index(drop=True)
df_v1_PSYCHOTROPES = df_PSYCHOTROPES[df_PSYCHOTROPES["NUM"] == "3"].reset_index(drop=True)
df_v3_PSYCHOTROPES = df_PSYCHOTROPES[df_PSYCHOTROPES["NUM"] == "4"].reset_index(drop=True)
df_v5_PSYCHOTROPES = df_PSYCHOTROPES[df_PSYCHOTROPES["NUM"] == "5"].reset_index(drop=True)

#### AUTRE_PARKINSON

In [153]:
df_AUTRE_PARKINSON = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="AUTRE_PARKINSON")
print(df_AUTRE_PARKINSON.shape)
df_AUTRE_PARKINSON.head()

(4176, 83)

,SUBJID,VISIT,NUM,Unnamed: 3,INIT_PAT,MEDICMT1,D_DEB1,POSO1,INDIC1,D_FIN1,...,POSO12,INDIC12,D_FIN12,ENCOURS12,MEDICMT13,D_DEB13,POSO13,INDIC13,D_FIN13,ENCOURS13
0,Subject Identifier for the Study,Visit,Num,NaN,initiales patient,médicament 1,date de début 1,posologie 1,indication 1,date de fin 1,...,posologie 12,indication 12,date de fin 12,en cours 12,médicament 13,date de début 13,posologie 13,indication 13,date de fin 13,en cours 13
1,01-001,Autres médicaments prescrits dans le cadre de ...,1,V0,SR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-001,Autres médicaments prescrits dans le cadre de ...,2,Vc,SR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,Autres médicaments prescrits dans le cadre de ...,3,V1,SR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,Autres médicaments prescrits dans le cadre de ...,4,V3,SR,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
df_AUTRE_PARKINSON["NUM"].value_counts()

NUM
1      835
2      835
3      835
4      835
5      835
Num      1
Name: count, dtype: int64

In [155]:
# Séparer le dataset par valeur de la colonne VISIT
df_V0_AUTRE_PARKINSON = df_AUTRE_PARKINSON[df_AUTRE_PARKINSON["NUM"] == "1"].reset_index(drop=True)
df_vc_AUTRE_PARKINSON = df_AUTRE_PARKINSON[df_AUTRE_PARKINSON["NUM"] == "2"].reset_index(drop=True)
df_v1_AUTRE_PARKINSON = df_AUTRE_PARKINSON[df_AUTRE_PARKINSON["NUM"] == "3"].reset_index(drop=True)
df_v3_AUTRE_PARKINSON = df_AUTRE_PARKINSON[df_AUTRE_PARKINSON["NUM"] == "4"].reset_index(drop=True)
df_v5_AUTRE_PARKINSON = df_AUTRE_PARKINSON[df_AUTRE_PARKINSON["NUM"] == "5"].reset_index(drop=True)

#### FREQUENCE_V1_3_5

In [157]:
df_FREQUENCE_V1_3_5 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="FREQUENCE_V1_3_5 ")
print(df_FREQUENCE_V1_3_5.shape)
df_FREQUENCE_V1_3_5.head()

(2506, 123)

,SUBJID,INIT_PAT,VISITE,PLOTG1,AMPLITUDEG1,UNITEG1,DUREEG1,FREQUENCEG1,IMPEDANCEG1,PLOTG2,...,NVUNITED4,NVDUREED4,NVFREQUENCED4,NVIMPEDANCED4,NVPLOTD5,NVAMPLITUED5,NVUNITED5,NVDUREED5,NVFREQUENCED5,NVIMPEDANCED5
0,Subject Identifier for the Study,initiales patient,visite,plot gauche 1,amplitude 1,unité 1,durée 1,fréquence 1,impédance 1,plot gauche 2,...,nouveau unité D4,nouveau durée D4,nouveau fréquence D4,nouveau impédance D4,nouveau plot droite 5,nouveau amplitude D5,nouveau unité D5,nouveau durée D5,nouveau fréquence D5,nouveau impédance D5
1,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-002,TM,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [159]:
df_FREQUENCE_V1_3_5["VISITE"].value_counts()

VISITE
Visite Bilan à 1 an - V1     835
Visite Bilan à 3 ans - V3    835
Visite Bilan à 5 ans - V5    835
visite                         1
Name: count, dtype: int64

In [161]:
# Séparer le dataset par valeur de la colonne VISITE
df_v1_FREQUENCE = df_FREQUENCE_V1_3_5[df_FREQUENCE_V1_3_5["VISITE"] == "Visite Bilan à 1 an - V1"].reset_index(drop=True)
df_v3_FREQUENCE = df_FREQUENCE_V1_3_5[df_FREQUENCE_V1_3_5["VISITE"] == "Visite Bilan à 3 ans - V3"].reset_index(drop=True)
df_v5_FREQUENCE = df_FREQUENCE_V1_3_5[df_FREQUENCE_V1_3_5["VISITE"] == "Visite Bilan à 5 ans - V5"].reset_index(drop=True)

#### DATES_VISITE

In [163]:
df_DATES_VISITE = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="DATES_VISITE")
print(df_DATES_VISITE.shape)
df_DATES_VISITE.head()

(836, 6)

,SUBJID,D_SCREEN,D_CHIR,DATE_V1,DATE_V3,DATE_V5
0,Subject Identifier for the Study,date de la visite de screening,date de l'intervention de la chirurgie,Date de la visite V1,Date de la visite V3,Date de la visite V5
1,01-001,18/11/2013,NaN,NaN,NaN,NaN
2,01-002,13/01/2014,NaN,NaN,NaN,NaN
3,01-003,04/03/2014,NaN,NaN,NaN,NaN
4,01-004,12/05/2014,23/09/2014,NaN,NaN,NaN

In [201]:
df_V0_DATES_VISITE = df_DATES_VISITE[["SUBJID","D_SCREEN"]]
df_vc_DATES_VISITE = df_DATES_VISITE[["SUBJID","D_CHIR"]]
df_v1_DATES_VISITE = df_DATES_VISITE[["SUBJID","DATE_V1"]]
df_v3_DATES_VISITE = df_DATES_VISITE[["SUBJID","DATE_V3"]]
df_v5_DATES_VISITE = df_DATES_VISITE[["SUBJID","DATE_V5"]]

#### FIN_ETUDE

In [171]:
df_FIN_ETUDEQUIP = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="FIN_ETUDE")
print(df_FIN_ETUDEQUIP.shape)
df_FIN_ETUDEQUIP.head()

(836, 9)

,SUBJID,SUIVI_ETUDE,D_FIN_ETUDE,D_SORTIE_PREMA,MOTIF_SORTIE_PREMA,AUTRE_PRECIS,D_INVESTIGATEUR,NOM_INVESTIGATEUR,MOTIF_SORTIE_PREMA1
0,Subject Identifier for the Study,suivi étude,date de fin de l'étude,date de sortie prématurée,motif de sortie prématurée,autre précision,date de signature de l'investigateur,nom de l'investigateur,motif de sortie prématurée LIB
1,01-001,0,NaN,22/11/2013,1,NaN,18/03/2014,MOREAU CAROLINE,Patient non opéré
2,01-002,0,NaN,20/02/2014,6,SUSPICION DE CANCER PULMONAIRE,24/03/2014,DR MOREAU,Autre
3,01-003,0,NaN,07/03/2014,1,NaN,21/03/2014,DR HOPES LUCIE,Patient non opéré
4,01-004,0,NaN,09/01/2015,6,RETRAIT DU MATERIEL ET RETRAIT DE CONSENTEMENT,09/01/2015,DEVOS,Autre

In [237]:
import pandas as pd

with pd.ExcelWriter("Output/info_statiques.xlsx", mode="a", engine="openpyxl") as writer:
    df_FIN_ETUDEQUIP.to_excel(writer, sheet_name="Sheet2", index=False)

#### Fichier Excel

In [214]:
df_v3

,SUBJID,INIT_PAT,TITRE,DATE,POIDS,POIDS_NR,TAILLE,TAILLE_NR
0,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN
1,01-002,TM,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN
2,01-003,SJ,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN
3,01-004,DJ,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN
4,01-005,LB,Visite Bilan à 3 ans - V3,17/04/2018,NaN,1,169,NaN
...,...,...,...,...,...,...,...,...
830,20-025,DA,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN
831,20-026,ME,Visite Bilan à 3 ans - V3,20/07/2022,121,NaN,187,NaN
832,20-027,RP,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN
833,20-028,DN,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN
834,20-029,DA,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN

In [223]:
import pandas as pd

lis = [name for name, val in globals().items() 
 if isinstance(val, pd.DataFrame) and name.startswith("df_v5")]
display(lis)
print(len(lis))

['df_v5',
 'df_v5_Feuil1',
 'df_v5_LEDD',
 'df_v5_PSYCHOTROPES',
 'df_v5_AUTRE_PARKINSON',
 'df_v5_FREQUENCE',
 'df_v5_CONSO_SPECIFIQUE',
 'df_v5_DIGITSMT_TRAILMT_DKEFS',
 'df_v5_PDQ39',
 'df_v5_LARS',
 'df_v5_HAMA',
 'df_v5_HAMD',
 'df_v5_MOCA',
 'df_v5_QUIP',
 'df_v5_ECMP',
 'df_v5_UPDRSIII_COMPLET',
 'df_v5_UPDRS',
 'df_v5_Poids_Taille',
 'df_v5_DATES_VISITE']

19

In [235]:
import pandas as pd

# ============================================================
#   DOSSIER DE SORTIE  (change si besoin)
# ============================================================
OUTPUT_DIR = "Output"   


# ============================================================
#   GROUPE 1 : fichier V0.xlsx
# ============================================================
sheets_V0 = {
    "DATES_VISITE"                 : df_V0_DATES_VISITE,
    "df_V0"                        : df_V0,
    "Feuil1"                       : df_V0_Feuil1,
    "LEDD"                         : df_V0_LEDD,
    "PSYCHOTROPES"                 : df_V0_PSYCHOTROPES,
    "AUTRE_PARKINSON"              : df_V0_AUTRE_PARKINSON,
    "CONSO_SPECIFIQUE"             : df_V0_CONSO_SPECIFIQUE,
    "DIGITSMT_TRAILMT_DKEFS"       : df_V0_DIGITSMT_TRAILMT_DKEFS,
    "PDQ39"                        : df_V0_PDQ39,
    "LARS"                         : df_V0_LARS,
    "HAMA"                         : df_V0_HAMA,
    "HAMD"                         : df_V0_HAMD,
    "MOCA"                         : df_V0_MOCA,
    "QUIP"                         : df_V0_QUIP,
    "ECMP"                         : df_V0_ECMP,
    "UPDRS"                        : df_V0_UPDRS,
    
}

# ============================================================
#   GROUPE 2 : fichier v1.xlsx
# ============================================================
sheets_v1 = {
    "DATES_VISITE"                 : df_v1_DATES_VISITE,
    "df_v1"                        : df_v1,
    "Feuil1"                       : df_v1_Feuil1,
    "LEDD"                         : df_v1_LEDD,
    "PSYCHOTROPES"                 : df_v1_PSYCHOTROPES,
    "AUTRE_PARKINSON"              : df_v1_AUTRE_PARKINSON,
    "FREQUENCE"                    : df_v1_FREQUENCE,
    "CONSO_SPECIFIQUE"             : df_v1_CONSO_SPECIFIQUE,
    "DIGITSMT_TRAILMT_DKEFS"       : df_v1_DIGITSMT_TRAILMT_DKEFS,
    "PDQ39"                        : df_v1_PDQ39,
    "LARS"                         : df_v1_LARS,
    "HAMA"                         : df_v1_HAMA,
    "HAMD"                         : df_v1_HAMD,
    "MOCA"                         : df_v1_MOCA,
    "QUIP"                         : df_v1_QUIP,
    "ECMP"                         : df_v1_ECMP,
    "UPDRS"                        : df_v1_UPDRS,
    "Poids_Taille"                 : df_v1_Poids_Taille,
}

# ============================================================
#   GROUPE 3 : fichier vc.xlsx
# ============================================================
sheets_vc = {
    "DATES_VISITE"                 : df_vc_DATES_VISITE,
    "CONSO_SPECIFIQUE"             : df_vc_CONSO_SPECIFIQUE,
    "Feuil1"                       : df_vc_Feuil1,
    "LEDD"                         : df_vc_LEDD,
    "PSYCHOTROPES"                 : df_vc_PSYCHOTROPES,
    "AUTRE_PARKINSON"              : df_vc_AUTRE_PARKINSON,
    "CONSO_SPECIFIQUE"             : df_vc_CONSO_SPECIFIQUE,
}

# ============================================================
#   GROUPE 4 : fichier v3.xlsx
# ============================================================
sheets_v3 = {
    "DATES_VISITE"                 : df_v3_DATES_VISITE,
    "df_v3"                        : df_v3,
    "Feuil1"                       : df_v3_Feuil1,
    "LEDD"                         : df_v3_LEDD,
    "PSYCHOTROPES"                 : df_v3_PSYCHOTROPES,
    "AUTRE_PARKINSON"              : df_v3_AUTRE_PARKINSON,
    "FREQUENCE"                    : df_v3_FREQUENCE,
    "CONSO_SPECIFIQUE"             : df_v3_CONSO_SPECIFIQUE,
    "DIGITSMT_TRAILMT_DKEFS"       : df_v3_DIGITSMT_TRAILMT_DKEFS,
    "PDQ39"                        : df_v3_PDQ39,
    "LARS"                         : df_v3_LARS,
    "HAMA"                         : df_v3_HAMA,
    "HAMD"                         : df_v3_HAMD,
    "MOCA"                         : df_v3_MOCA,
    "QUIP"                         : df_v3_QUIP,
    "ECMP"                         : df_v3_ECMP,
    "UPDRSIII_COMPLET"             : df_v3_UPDRSIII_COMPLET,
    "UPDRS"                        : df_v3_UPDRS,
    "Poids_Taille"                 : df_v3_Poids_Taille,
}

# ============================================================
#   GROUPE 5 : fichier v5.xlsx
# ============================================================
sheets_v5 = {
    "DATES_VISITE"                 : df_v5_DATES_VISITE,
    "df_v5"                        : df_v5,
    "Feuil1"                       : df_v5_Feuil1,
    "LEDD"                         : df_v5_LEDD,
    "PSYCHOTROPES"                 : df_v5_PSYCHOTROPES,
    "AUTRE_PARKINSON"              : df_v5_AUTRE_PARKINSON,
    "FREQUENCE"                    : df_v5_FREQUENCE,
    "CONSO_SPECIFIQUE"             : df_v5_CONSO_SPECIFIQUE,
    "DIGITSMT_TRAILMT_DKEFS"       : df_v5_DIGITSMT_TRAILMT_DKEFS,
    "PDQ39"                        : df_v5_PDQ39,
    "LARS"                         : df_v5_LARS,
    "HAMA"                         : df_v5_HAMA,
    "HAMD"                         : df_v5_HAMD,
    "MOCA"                         : df_v5_MOCA,
    "QUIP"                         : df_v5_QUIP,
    "ECMP"                         : df_v5_ECMP,
    "UPDRSIII_COMPLET"             : df_v5_UPDRSIII_COMPLET,
    "UPDRS"                        : df_v5_UPDRS,
    "Poids_Taille"                 : df_v5_Poids_Taille,
}


# ─── Ne touche pas au code en dessous ───────────────────────

all_groups = {
    "V0" : sheets_V0,
    "v1" : sheets_v1,
    "vc" : sheets_vc,
    "v3" : sheets_v3,
    "v5" : sheets_v5,
}

for version, sheets in all_groups.items():
    filepath = f"{OUTPUT_DIR}/{version}.xlsx"
    with pd.ExcelWriter(filepath, engine="openpyxl") as writer:
        for sheet_name, df in sheets.items():
            df.to_excel(writer, sheet_name=sheet_name[:31], index=False)
    print(f"[OK] {filepath}  →  {len(sheets)} feuilles")

[OK] Output/V0.xlsx  →  16 feuilles
[OK] Output/v1.xlsx  →  18 feuilles
[OK] Output/vc.xlsx  →  6 feuilles
[OK] Output/v3.xlsx  →  19 feuilles
[OK] Output/v5.xlsx  →  19 feuilles

In [ ]:
df

### Bilan V0

In [76]:
df_V0 = pd.read_excel("Data/Matthieu_Soumaya_Dec2025.xlsx", sheet_name="Poids_Taille V0")
print(df_V0.shape)
df_V0.head()

(836, 7)

,SUBJID,INIT_PAT,TITRE,POIDS,POIDS_NR,TAILLE,TAILLE_NR
0,Subject Identifier for the Study,initiales patient,titre,poids,poids non réalisé,taille,taille non réalisé
1,01-001,SR,Visite de screening,76,NaN,171,NaN
2,01-002,TM,Visite de screening,88,NaN,180,NaN
3,01-003,SJ,Visite de screening,89,NaN,176,NaN
4,01-004,DJ,Visite de screening,59,NaN,163,NaN

(3341, 10)

,SUBJID,INIT_PAT,TITRE,MDSUPDRSPARTIE4,MDSUPDRSPARTIE41,MDSUPDRSPARTIE42,MDSUPDRSPARTIE43,MDSUPDRSPARTIE44,MDSUPDRSPARTIE45,MDSUPDRSPARTIE46
0,Subject Identifier for the Study,initiales patient,titre,MDS-UPDRS partie 4,MDS-UPDRS partie 4.1,MDS-UPDRS partie 4.2,MDS-UPDRS partie 4.3,MDS-UPDRS partie 4.4,MDS-UPDRS partie 4.5,MDS-UPDRS partie 4.6
1,01-001,SR,Visite de screening,10,Minime,Modéré,Léger,Modéré,Minime,Normal
2,01-001,SR,Visite Bilan à 1 an - V1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-001,SR,Visite Bilan à 3 ans - V3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-001,SR,Visite Bilan à 5 ans - V5,NaN,NaN,NaN,NaN,NaN,NaN,NaN